//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string CapNhat {
            get {
                return ResourceManager.GetString("CapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn File.
        /// </summary>
        internal static string ChonFile {
            get {
                return ResourceManager.GetString("ChonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string DenNgay {
            get {
                return ResourceManager.GetString("DenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Đặt Hàng.
        /// </summary>
        internal static string DonDatHang {
            get {
                return ResourceManager.GetString("DonDatHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Flie Excel.
        /// </summary>
        internal static string ImPortExcel {
            get {
                return ResourceManager.GetString("ImPortExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Dùng.
        /// </summary>
        internal static string NguoiDung {
            get {
                return ResourceManager.GetString("NguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string NhaCungCap {
            get {
                return ResourceManager.GetString("NhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burden Furniture.
        /// </summary>
        internal static string TenCongTy {
            get {
                return ResourceManager.GetString("TenCongTy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burden Warehouse Management.
        /// </summary>
        internal static string TenWeb {
            get {
                return ResourceManager.GetString("TenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string ThemMoi {
            get {
                return ResourceManager.GetString("ThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string TimKiem {
            get {
                return ResourceManager.GetString("TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string TuNgay {
            get {
                return ResourceManager.GetString("TuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Xoa {
            get {
                return ResourceManager.GetString("Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất File.
        /// </summary>
        internal static string XuatFile {
            get {
                return ResourceManager.GetString("XuatFile", resourceCulture);
            }
        }
    }
}
