//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Theo Dõi Nhập K-H-Tr.
        /// </summary>
        internal static string BaoCaoNhapHang {
            get {
                return ResourceManager.GetString("BaoCaoNhapHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo Cáo Tiến Độ Sản Xuất.
        /// </summary>
        internal static string BaoCaoTienDoSanXuat {
            get {
                return ResourceManager.GetString("BaoCaoTienDoSanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Kệ Hàng Trắng.
        /// </summary>
        internal static string ChuyenKe {
            get {
                return ResourceManager.GetString("ChuyenKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Kệ Thành Phẩm.
        /// </summary>
        internal static string ChuyenKeThanhPham {
            get {
                return ResourceManager.GetString("ChuyenKeThanhPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Kệ.
        /// </summary>
        internal static string DMKe {
            get {
                return ResourceManager.GetString("DMKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Nhà Cung Cấp.
        /// </summary>
        internal static string DMNhaCungCap {
            get {
                return ResourceManager.GetString("DMNhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho Hàng Trắng Chi Tiết.
        /// </summary>
        internal static string HangTrangChiTiet {
            get {
                return ResourceManager.GetString("HangTrangChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Xuất.
        /// </summary>
        internal static string LenhRaiHang {
            get {
                return ResourceManager.GetString("LenhRaiHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Chuyển Kệ Hàng Trắng.
        /// </summary>
        internal static string LichSuChuyenKe {
            get {
                return ResourceManager.GetString("LichSuChuyenKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Chuyển Kệ Thành Phẩm.
        /// </summary>
        internal static string LichSuChuyenKeThanhPham {
            get {
                return ResourceManager.GetString("LichSuChuyenKeThanhPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Quét Sản Xuất.
        /// </summary>
        internal static string LichSuQuetSanXuat {
            get {
                return ResourceManager.GetString("LichSuQuetSanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Xuất Kệ Hàng Trắng.
        /// </summary>
        internal static string LichSuXuatKeHangTrang {
            get {
                return ResourceManager.GetString("LichSuXuatKeHangTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm Người Dùng.
        /// </summary>
        internal static string NhomNguoiDung {
            get {
                return ResourceManager.GetString("NhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu Nhập Hàng.
        /// </summary>
        internal static string PhieuNhapHang {
            get {
                return ResourceManager.GetString("PhieuNhapHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu Xuất Kệ Hàng Trắng.
        /// </summary>
        internal static string PhieuXuatKeHangTrang {
            get {
                return ResourceManager.GetString("PhieuXuatKeHangTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In QR Code 1.
        /// </summary>
        internal static string QRCode1 {
            get {
                return ResourceManager.GetString("QRCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In QR Code 1 Theo Số OF.
        /// </summary>
        internal static string QRCode1TuChon {
            get {
                return ResourceManager.GetString("QRCode1TuChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In QR Code 2.
        /// </summary>
        internal static string QRCode2 {
            get {
                return ResourceManager.GetString("QRCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In QR Code 2 Theo Số OF.
        /// </summary>
        internal static string QRCode2TuChon {
            get {
                return ResourceManager.GetString("QRCode2TuChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Dùng.
        /// </summary>
        internal static string QuanLyNguoiDung {
            get {
                return ResourceManager.GetString("QuanLyNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho Thành Phẩm Chi Tiết.
        /// </summary>
        internal static string ThanhPhamChiTiet {
            get {
                return ResourceManager.GetString("ThanhPhamChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Dõi Nhập Kệ Thành Phẩm.
        /// </summary>
        internal static string TheoDoiNhapKeThanhPham {
            get {
                return ResourceManager.GetString("TheoDoiNhapKeThanhPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Dõi Xuất Kệ Thành Phẩm.
        /// </summary>
        internal static string TheoDoiXuatKeThanhPham {
            get {
                return ResourceManager.GetString("TheoDoiXuatKeThanhPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Tiến Độ SX Tổng.
        /// </summary>
        internal static string ThongTinTienDoSanXuat {
            get {
                return ResourceManager.GetString("ThongTinTienDoSanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Tiến Độ SX Chi Tiết.
        /// </summary>
        internal static string ThongTinTienDoSanXuatChiTiet {
            get {
                return ResourceManager.GetString("ThongTinTienDoSanXuatChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng QR2 sản xuất.
        /// </summary>
        internal static string TinhTrangQR2SanXuat {
            get {
                return ResourceManager.GetString("TinhTrangQR2SanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng Hợp Kệ Hàng Trắng.
        /// </summary>
        internal static string TongHopKeHangTrang {
            get {
                return ResourceManager.GetString("TongHopKeHangTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Dõi Tổng Hợp K-Th-Ph.
        /// </summary>
        internal static string TongHopKeThanhPham {
            get {
                return ResourceManager.GetString("TongHopKeThanhPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo Cáo Tổng Nhập Xuất Theo Mã SKU.
        /// </summary>
        internal static string TongTonTheoMaSKU {
            get {
                return ResourceManager.GetString("TongTonTheoMaSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất File C.I.R.S.
        /// </summary>
        internal static string XuatFileCIRS {
            get {
                return ResourceManager.GetString("XuatFileCIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất File CLS.
        /// </summary>
        internal static string XuatFileCLS {
            get {
                return ResourceManager.GetString("XuatFileCLS", resourceCulture);
            }
        }
    }
}
