//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_LichSuInQRCode1
    {
        public long ID { get; set; }
        public long IDPoChiTiet { get; set; }
        public int TuSo { get; set; }
        public int DenSo { get; set; }
        public System.DateTime NgayIn { get; set; }
        public int NguoiDungIn { get; set; }
        public string MaSKU { get; set; }
    }
}
