//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_LichSuChuyenKeThanhPham
    {
        public long Id { get; set; }
        public long IdNhapKhoThanhPham { get; set; }
        public long IDLenhRaiHang { get; set; }
        public int IdKeCu { get; set; }
        public int IdKeMoi { get; set; }
        public int NguoiDungChuyen { get; set; }
        public System.DateTime NgayChuyen { get; set; }
        public string QRCode { get; set; }
        public Nullable<int> SoNumOf { get; set; }
    }
}
