//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_LenhRaiHang
    {
        public long IDLenhRaiHang { get; set; }
        public string SoEPI { get; set; }
        public string MaChiTietSanPham { get; set; }
        public string SoPO { get; set; }
        public string MaSanPham { get; set; }
        public string MaKH { get; set; }
        public string MoTa { get; set; }
        public string MaPhoiHop { get; set; }
        public string KichThuocSanPham { get; set; }
        public string MaMauOrVai { get; set; }
        public string ODM { get; set; }
        public Nullable<int> SoLuongEPI { get; set; }
        public Nullable<int> TongSoLuongTrongNX { get; set; }
        public Nullable<int> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> Del { get; set; }
        public string TayNam { get; set; }
        public string MaThung { get; set; }
        public string MauTrong { get; set; }
        public string LoaiDongGoi { get; set; }
    }
}
