//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_NhapKhoThanhPham
    {
        public long Id { get; set; }
        public long IDLenhRaiHang { get; set; }
        public int SoNumOf { get; set; }
        public int IdKe { get; set; }
        public int NguoiDungNhapKho { get; set; }
        public System.DateTime NgayNhapKho { get; set; }
        public Nullable<bool> XuatKho { get; set; }
        public Nullable<int> NguoiDungXuat { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string QRCode { get; set; }
        public Nullable<bool> Del { get; set; }
        public string EPINumber { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> NguoiLenCont { get; set; }
        public Nullable<System.DateTime> NgayLenCont { get; set; }
        public string GhiChu { get; set; }
    }
}
