//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_PhieuNhapHang
    {
        public long IdPhieuNhapHang { get; set; }
        public string SoPhieu { get; set; }
        public int IdNhaCungCap { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public Nullable<int> IdNguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> IdNguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> INTL { get; set; }
        public Nullable<bool> VN { get; set; }
        public Nullable<bool> Go { get; set; }
        public Nullable<bool> PhuKien { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
