//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD_QuetSanXuat
    {
        public long Id { get; set; }
        public long IDLenhRaiHang { get; set; }
        public int SoNumOf { get; set; }
        public string MaCongDoan { get; set; }
        public bool Tinh { get; set; }
        public int NguoiDungQuet { get; set; }
        public System.DateTime NgayQuet { get; set; }
        public Nullable<int> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string LyDoSua { get; set; }
        public string QRCode2 { get; set; }
        public Nullable<System.DateTime> NgayQuetTru { get; set; }
        public Nullable<int> NguoiQuetTru { get; set; }
    }
}
