//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_CongDoan
    {
        public string MaCongDoan { get; set; }
        public string TenCongDoan { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> KiemTra { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
    }
}
