//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_Menu
    {
        public int MenuIndex { get; set; }
        public string MenuName { get; set; }
        public string MenuColor { get; set; }
        public string MenuAction { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
