//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_NhaCungCap
    {
        public int IdNhaCungCap { get; set; }
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
