//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_HistoryEditData
    {
        public long ID { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string KeyRow { get; set; }
        public string TableName { get; set; }
        public Nullable<int> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
