//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_PhamViCongDoan
    {
        public long IdPhamVi { get; set; }
        public Nullable<long> IdDoiTuong { get; set; }
        public Nullable<bool> LaNguoiDung { get; set; }
        public string MaPhamVi { get; set; }
    }
}
