//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Quyen
    {
        public int IdQuyen { get; set; }
        public string TenQuyen { get; set; }
        public Nullable<int> SapXep { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public Nullable<int> IdNhomQuyen { get; set; }
    }
}
