//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BD_LenhRaiHang> BD_LenhRaiHang { get; set; }
        public virtual DbSet<BD_PhieuNhapHang> BD_PhieuNhapHang { get; set; }
        public virtual DbSet<BD_PhieuNhapHangChiTiet> BD_PhieuNhapHangChiTiet { get; set; }
        public virtual DbSet<BD_Po> BD_Po { get; set; }
        public virtual DbSet<BD_POChiTiet> BD_POChiTiet { get; set; }
        public virtual DbSet<HT_NhomNguoiDung> HT_NhomNguoiDung { get; set; }
        public virtual DbSet<HT_NhomQuyen> HT_NhomQuyen { get; set; }
        public virtual DbSet<HT_Quyen> HT_Quyen { get; set; }
        public virtual DbSet<HT_SQL> HT_SQL { get; set; }
        public virtual DbSet<HS_CongDoan> HS_CongDoan { get; set; }
        public virtual DbSet<HS_Ke> HS_Ke { get; set; }
        public virtual DbSet<BD_LichSuChuyenKe> BD_LichSuChuyenKe { get; set; }
        public virtual DbSet<Sys_CauHinh> Sys_CauHinh { get; set; }
        public virtual DbSet<BD_NhapKhoThanhPham> BD_NhapKhoThanhPham { get; set; }
        public virtual DbSet<BD_QuetSanXuat> BD_QuetSanXuat { get; set; }
        public virtual DbSet<HT_NguoiDung> HT_NguoiDung { get; set; }
        public virtual DbSet<HT_PhamViCongDoan> HT_PhamViCongDoan { get; set; }
        public virtual DbSet<BD_LichSuChuyenKeThanhPham> BD_LichSuChuyenKeThanhPham { get; set; }
        public virtual DbSet<HS_Menu> HS_Menu { get; set; }
        public virtual DbSet<HT_PhanQuyen> HT_PhanQuyen { get; set; }
        public virtual DbSet<HS_TrangThaiNhapKhoTP> HS_TrangThaiNhapKhoTP { get; set; }
        public virtual DbSet<BD_LichSuInQRCode1> BD_LichSuInQRCode1 { get; set; }
        public virtual DbSet<HT_HistoryEditData> HT_HistoryEditData { get; set; }
        public virtual DbSet<HS_NhaCungCap> HS_NhaCungCap { get; set; }
    
        public virtual ObjectResult<App_DanhSachPhieuNhapHang_Result> App_DanhSachPhieuNhapHang(Nullable<int> nguoiDung, string search)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_DanhSachPhieuNhapHang_Result>("App_DanhSachPhieuNhapHang", nguoiDungParameter, searchParameter);
        }
    
        public virtual ObjectResult<PR_ThongTinNguoiDung_Result> PR_ThongTinNguoiDung(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ThongTinNguoiDung_Result>("PR_ThongTinNguoiDung", usernameParameter);
        }
    
        public virtual ObjectResult<BD_InQRCode1_Result> BD_InQRCode1(string soPo)
        {
            var soPoParameter = soPo != null ?
                new ObjectParameter("SoPo", soPo) :
                new ObjectParameter("SoPo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_InQRCode1_Result>("BD_InQRCode1", soPoParameter);
        }
    
        public virtual ObjectResult<BD_InQRCode2_Result> BD_InQRCode2(string soEPI)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_InQRCode2_Result>("BD_InQRCode2", soEPIParameter);
        }
    
        public virtual ObjectResult<BD_ChuyenKe_Result> BD_ChuyenKe(string maKe)
        {
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_ChuyenKe_Result>("BD_ChuyenKe", maKeParameter);
        }
    
        public virtual ObjectResult<BC_TheoDoiXuatKeHangTrang_Result> BC_TheoDoiXuatKeHangTrang(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maKe, string soEPI, string maSKU, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BC_TheoDoiXuatKeHangTrang_Result>("BC_TheoDoiXuatKeHangTrang", tuNgayParameter, denNgayParameter, maKeParameter, soEPIParameter, maSKUParameter, maSPParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKe_ChiTiet_Result> App_ChuyenKe_ChiTiet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKe_ChiTiet_Result>("App_ChuyenKe_ChiTiet", idParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKe_ChiTiet_Ke_Result> App_ChuyenKe_ChiTiet_Ke(Nullable<int> idKe)
        {
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKe_ChiTiet_Ke_Result>("App_ChuyenKe_ChiTiet_Ke", idKeParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKe_DanhSach_Result> App_ChuyenKe_DanhSach(Nullable<int> nguoiDung, string search)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKe_DanhSach_Result>("App_ChuyenKe_DanhSach", nguoiDungParameter, searchParameter);
        }
    
        public virtual ObjectResult<App_PhieuNhapHang_ChiTiet_Result> App_PhieuNhapHang_ChiTiet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_PhieuNhapHang_ChiTiet_Result>("App_PhieuNhapHang_ChiTiet", idParameter);
        }
    
        public virtual ObjectResult<App_PhieuNhapHang_ChiTiet_Ke_Result> App_PhieuNhapHang_ChiTiet_Ke(Nullable<int> ke)
        {
            var keParameter = ke.HasValue ?
                new ObjectParameter("Ke", ke) :
                new ObjectParameter("Ke", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_PhieuNhapHang_ChiTiet_Ke_Result>("App_PhieuNhapHang_ChiTiet_Ke", keParameter);
        }
    
        public virtual ObjectResult<App_PhieuNhapHang_DanhSach_Result> App_PhieuNhapHang_DanhSach(Nullable<int> nguoiDung, string search)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_PhieuNhapHang_DanhSach_Result>("App_PhieuNhapHang_DanhSach", nguoiDungParameter, searchParameter);
        }
    
        public virtual ObjectResult<App_PhieuNhapHang_UpdateQRCode_Result> App_PhieuNhapHang_UpdateQRCode(Nullable<int> nguoiDung, Nullable<int> idKe, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_PhieuNhapHang_UpdateQRCode_Result>("App_PhieuNhapHang_UpdateQRCode", nguoiDungParameter, idKeParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<Backup_App_PhieuNhapHang_UpdateQRCode_Result> Backup_App_PhieuNhapHang_UpdateQRCode(Nullable<int> nguoiDung, Nullable<int> idPhieuNhapHang, string soPhieu, Nullable<int> idKe, string soPO, string soLichGiaoHang, string maSanPham, string maChiTietSanPham, string tenChiTietSanPham, string donViTinh, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idPhieuNhapHangParameter = idPhieuNhapHang.HasValue ?
                new ObjectParameter("IdPhieuNhapHang", idPhieuNhapHang) :
                new ObjectParameter("IdPhieuNhapHang", typeof(int));
    
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("SoPhieu", soPhieu) :
                new ObjectParameter("SoPhieu", typeof(string));
    
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            var soPOParameter = soPO != null ?
                new ObjectParameter("SoPO", soPO) :
                new ObjectParameter("SoPO", typeof(string));
    
            var soLichGiaoHangParameter = soLichGiaoHang != null ?
                new ObjectParameter("SoLichGiaoHang", soLichGiaoHang) :
                new ObjectParameter("SoLichGiaoHang", typeof(string));
    
            var maSanPhamParameter = maSanPham != null ?
                new ObjectParameter("MaSanPham", maSanPham) :
                new ObjectParameter("MaSanPham", typeof(string));
    
            var maChiTietSanPhamParameter = maChiTietSanPham != null ?
                new ObjectParameter("MaChiTietSanPham", maChiTietSanPham) :
                new ObjectParameter("MaChiTietSanPham", typeof(string));
    
            var tenChiTietSanPhamParameter = tenChiTietSanPham != null ?
                new ObjectParameter("TenChiTietSanPham", tenChiTietSanPham) :
                new ObjectParameter("TenChiTietSanPham", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Backup_App_PhieuNhapHang_UpdateQRCode_Result>("Backup_App_PhieuNhapHang_UpdateQRCode", nguoiDungParameter, idPhieuNhapHangParameter, soPhieuParameter, idKeParameter, soPOParameter, soLichGiaoHangParameter, maSanPhamParameter, maChiTietSanPhamParameter, tenChiTietSanPhamParameter, donViTinhParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<PP_LichSuChyenKe_Result> PP_LichSuChyenKe(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> nguoiDung, string maSKU, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PP_LichSuChyenKe_Result>("PP_LichSuChyenKe", tuNgayParameter, denNgayParameter, nguoiDungParameter, maSKUParameter, maSPParameter);
        }
    
        public virtual ObjectResult<App_DanhSachQuetNhapKhoThanhPham_Result> App_DanhSachQuetNhapKhoThanhPham(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_DanhSachQuetNhapKhoThanhPham_Result>("App_DanhSachQuetNhapKhoThanhPham", nguoiDungParameter);
        }
    
        public virtual ObjectResult<BD_TienDoSanXuat1_Result> BD_TienDoSanXuat1(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_TienDoSanXuat1_Result>("BD_TienDoSanXuat1", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTienDoSanXuat1_Result> BD_BaoCaoTienDoSanXuat1(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTienDoSanXuat1_Result>("BD_BaoCaoTienDoSanXuat1", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTienDoSanXuatChiTiet1_Result> BD_BaoCaoTienDoSanXuatChiTiet1(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTienDoSanXuatChiTiet1_Result>("BD_BaoCaoTienDoSanXuatChiTiet1", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<App_NhapThanhPham_Result> App_NhapThanhPham(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhapThanhPham_Result>("App_NhapThanhPham", nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_NhapThanhPham_UpdateQRCode_Result> App_NhapThanhPham_UpdateQRCode(Nullable<int> nguoiDung, Nullable<int> idKe, Nullable<int> idLenh, Nullable<int> numOf, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            var idLenhParameter = idLenh.HasValue ?
                new ObjectParameter("IdLenh", idLenh) :
                new ObjectParameter("IdLenh", typeof(int));
    
            var numOfParameter = numOf.HasValue ?
                new ObjectParameter("NumOf", numOf) :
                new ObjectParameter("NumOf", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhapThanhPham_UpdateQRCode_Result>("App_NhapThanhPham_UpdateQRCode", nguoiDungParameter, idKeParameter, idLenhParameter, numOfParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_XuatContainer_Result> App_XuatContainer(string soEPI, Nullable<int> nguoiDung)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatContainer_Result>("App_XuatContainer", soEPIParameter, nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_XuatContainer_UpdateQRCode_Result> App_XuatContainer_UpdateQRCode(Nullable<int> nguoiDung, string soEPI, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatContainer_UpdateQRCode_Result>("App_XuatContainer_UpdateQRCode", nguoiDungParameter, soEPIParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_Result> App_XuatHangTrang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_Result>("App_XuatHangTrang", idParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_ChiTiet_Result> App_XuatHangTrang_ChiTiet(string soEPI)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_ChiTiet_Result>("App_XuatHangTrang_ChiTiet", soEPIParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_Ke_Result> App_XuatHangTrang_Ke(string soEPI)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_Ke_Result>("App_XuatHangTrang_Ke", soEPIParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_UpdateQRCode_Result> App_XuatHangTrang_UpdateQRCode(Nullable<int> nguoiDung, string soEPI, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_UpdateQRCode_Result>("App_XuatHangTrang_UpdateQRCode", nguoiDungParameter, soEPIParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTheoDoiKeThanhPham_Result> BD_BaoCaoTheoDoiKeThanhPham(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maSKU, string maKe, string maSP, string soEPI)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTheoDoiKeThanhPham_Result>("BD_BaoCaoTheoDoiKeThanhPham", tuNgayParameter, denNgayParameter, maSKUParameter, maKeParameter, maSPParameter, soEPIParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_DanhSach_Result> App_SanXuat_DanhSach(string timKiem)
        {
            var timKiemParameter = timKiem != null ?
                new ObjectParameter("TimKiem", timKiem) :
                new ObjectParameter("TimKiem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_DanhSach_Result>("App_SanXuat_DanhSach", timKiemParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_EPI_Result> App_SanXuat_EPI(string timKiem)
        {
            var timKiemParameter = timKiem != null ?
                new ObjectParameter("TimKiem", timKiem) :
                new ObjectParameter("TimKiem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_EPI_Result>("App_SanXuat_EPI", timKiemParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTongHopKeHangTrang_Result> BD_BaoCaoTongHopKeHangTrang(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maSKU, string maSP, string maKe)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTongHopKeHangTrang_Result>("BD_BaoCaoTongHopKeHangTrang", tuNgayParameter, denNgayParameter, maSKUParameter, maSPParameter, maKeParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_DanhSach_ChiTiet_Result> App_SanXuat_DanhSach_ChiTiet(string maCongDoan)
        {
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_DanhSach_ChiTiet_Result>("App_SanXuat_DanhSach_ChiTiet", maCongDoanParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_DanhSach_ChiTietTru_Result> App_SanXuat_DanhSach_ChiTietTru(string maCongDoan)
        {
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_DanhSach_ChiTietTru_Result>("App_SanXuat_DanhSach_ChiTietTru", maCongDoanParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_KTCongDoan_Result> App_SanXuat_KTCongDoan(Nullable<int> nguoiDung, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_KTCongDoan_Result>("App_SanXuat_KTCongDoan", nguoiDungParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_UpdateQrCode_Result> App_SanXuat_UpdateQrCode(Nullable<int> nguoiDung, string maCongDoan, Nullable<int> stt, Nullable<int> idLenhRaiHang, Nullable<int> numOf, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            var sttParameter = stt.HasValue ?
                new ObjectParameter("Stt", stt) :
                new ObjectParameter("Stt", typeof(int));
    
            var idLenhRaiHangParameter = idLenhRaiHang.HasValue ?
                new ObjectParameter("IdLenhRaiHang", idLenhRaiHang) :
                new ObjectParameter("IdLenhRaiHang", typeof(int));
    
            var numOfParameter = numOf.HasValue ?
                new ObjectParameter("NumOf", numOf) :
                new ObjectParameter("NumOf", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_UpdateQrCode_Result>("App_SanXuat_UpdateQrCode", nguoiDungParameter, maCongDoanParameter, sttParameter, idLenhRaiHangParameter, numOfParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_UpdateQrCodeTruCD_Result> App_SanXuat_UpdateQrCodeTruCD(Nullable<int> nguoiDung, string soEPI, string maCongDoan, string lyDo, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_UpdateQrCodeTruCD_Result>("App_SanXuat_UpdateQrCodeTruCD", nguoiDungParameter, soEPIParameter, maCongDoanParameter, lyDoParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_GetEPI_Result> App_GetEPI(Nullable<int> step)
        {
            var stepParameter = step.HasValue ?
                new ObjectParameter("Step", step) :
                new ObjectParameter("Step", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_GetEPI_Result>("App_GetEPI", stepParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTienDoSanXuat_Result> BD_BaoCaoTienDoSanXuat(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string soEPI)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTienDoSanXuat_Result>("BD_BaoCaoTienDoSanXuat", tuNgayParameter, denNgayParameter, soEPIParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTienDoSanXuatChiTiet_Result> BD_BaoCaoTienDoSanXuatChiTiet(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maCongDoan, string soEPI)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTienDoSanXuatChiTiet_Result>("BD_BaoCaoTienDoSanXuatChiTiet", tuNgayParameter, denNgayParameter, maCongDoanParameter, soEPIParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoNhapHangTrang_Result> BD_BaoCaoNhapHangTrang(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maSKU, string maKe, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoNhapHangTrang_Result>("BD_BaoCaoNhapHangTrang", tuNgayParameter, denNgayParameter, maSKUParameter, maKeParameter, maSPParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTheoDoiNhapKeThanhPham_Result> BD_BaoCaoTheoDoiNhapKeThanhPham(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maSKU, string maKe, string maSP, string soEPI)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTheoDoiNhapKeThanhPham_Result>("BD_BaoCaoTheoDoiNhapKeThanhPham", tuNgayParameter, denNgayParameter, maSKUParameter, maKeParameter, maSPParameter, soEPIParameter);
        }
    
        public virtual ObjectResult<BD_TheoDoiXuatKeThanhPham_Result> BD_TheoDoiXuatKeThanhPham(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maSKU, string maKe, string soEPI, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_TheoDoiXuatKeThanhPham_Result>("BD_TheoDoiXuatKeThanhPham", tuNgayParameter, denNgayParameter, maSKUParameter, maKeParameter, soEPIParameter, maSPParameter);
        }
    
        public virtual ObjectResult<BD_LayThongTinCLS_Result> BD_LayThongTinCLS(string soEPI)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_LayThongTinCLS_Result>("BD_LayThongTinCLS", soEPIParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKeThanhPham_UpdateKe_Result> App_ChuyenKeThanhPham_UpdateKe(Nullable<int> nguoiDung, Nullable<int> idKe, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKeThanhPham_UpdateKe_Result>("App_ChuyenKeThanhPham_UpdateKe", nguoiDungParameter, idKeParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKeThanhPham_ChiTietKe_Result> App_ChuyenKeThanhPham_ChiTietKe(Nullable<int> nguoiDung, Nullable<int> idKe)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idKeParameter = idKe.HasValue ?
                new ObjectParameter("IdKe", idKe) :
                new ObjectParameter("IdKe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKeThanhPham_ChiTietKe_Result>("App_ChuyenKeThanhPham_ChiTietKe", nguoiDungParameter, idKeParameter);
        }
    
        public virtual ObjectResult<App_SoanHangXuatContainer_Result> App_SoanHangXuatContainer(string soEPI, Nullable<int> nguoiDung)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SoanHangXuatContainer_Result>("App_SoanHangXuatContainer", soEPIParameter, nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_SoanHangXuatContainer_UpdateQRCode_Result> App_SoanHangXuatContainer_UpdateQRCode(Nullable<int> nguoiDung, string soEPI, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SoanHangXuatContainer_UpdateQRCode_Result>("App_SoanHangXuatContainer_UpdateQRCode", nguoiDungParameter, soEPIParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_Menu_Result> App_Menu(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Menu_Result>("App_Menu", nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_NhanHang_ChiTiet_Result> App_NhanHang_ChiTiet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhanHang_ChiTiet_Result>("App_NhanHang_ChiTiet", idParameter);
        }
    
        public virtual ObjectResult<App_NhanHang_ChiTiet_Ke_Result> App_NhanHang_ChiTiet_Ke(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhanHang_ChiTiet_Ke_Result>("App_NhanHang_ChiTiet_Ke", idParameter);
        }
    
        public virtual ObjectResult<App_NhanHang_DanhSach_Result> App_NhanHang_DanhSach(Nullable<int> nguoiDung, string search)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhanHang_DanhSach_Result>("App_NhanHang_DanhSach", nguoiDungParameter, searchParameter);
        }
    
        public virtual ObjectResult<App_NhanHang_UpdateQRCode_Result> App_NhanHang_UpdateQRCode(Nullable<int> nguoiDung, Nullable<int> idPhieuNhapHang, string soPhieu, Nullable<int> idPOChiTiet, Nullable<int> num, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var idPhieuNhapHangParameter = idPhieuNhapHang.HasValue ?
                new ObjectParameter("IdPhieuNhapHang", idPhieuNhapHang) :
                new ObjectParameter("IdPhieuNhapHang", typeof(int));
    
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("SoPhieu", soPhieu) :
                new ObjectParameter("SoPhieu", typeof(string));
    
            var idPOChiTietParameter = idPOChiTiet.HasValue ?
                new ObjectParameter("IdPOChiTiet", idPOChiTiet) :
                new ObjectParameter("IdPOChiTiet", typeof(int));
    
            var numParameter = num.HasValue ?
                new ObjectParameter("Num", num) :
                new ObjectParameter("Num", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_NhanHang_UpdateQRCode_Result>("App_NhanHang_UpdateQRCode", nguoiDungParameter, idPhieuNhapHangParameter, soPhieuParameter, idPOChiTietParameter, numParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_ChuyenKeThanhPham_ChiTiet_Result> App_ChuyenKeThanhPham_ChiTiet(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_ChuyenKeThanhPham_ChiTiet_Result>("App_ChuyenKeThanhPham_ChiTiet", nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_GetCongDoan_Result> App_GetCongDoan(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_GetCongDoan_Result>("App_GetCongDoan", nguoiDungParameter);
        }
    
        public virtual ObjectResult<BD_LichSuChyenKeThanhPham_Result> BD_LichSuChyenKeThanhPham(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> nguoiDung, string maSKU, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_LichSuChyenKeThanhPham_Result>("BD_LichSuChyenKeThanhPham", tuNgayParameter, denNgayParameter, nguoiDungParameter, maSKUParameter, maSPParameter);
        }
    
        public virtual ObjectResult<BD_DashboarddBaoCaoTienDoSanXuat_Result> BD_DashboarddBaoCaoTienDoSanXuat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_DashboarddBaoCaoTienDoSanXuat_Result>("BD_DashboarddBaoCaoTienDoSanXuat");
        }
    
        public virtual ObjectResult<BD_InQRCode2TuChon_Result> BD_InQRCode2TuChon(string soEPI, string maSKU)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_InQRCode2TuChon_Result>("BD_InQRCode2TuChon", soEPIParameter, maSKUParameter);
        }
    
        public virtual ObjectResult<BD_InQRCode1TuChon_Result> BD_InQRCode1TuChon(string soPo, string maSKU)
        {
            var soPoParameter = soPo != null ?
                new ObjectParameter("SoPo", soPo) :
                new ObjectParameter("SoPo", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_InQRCode1TuChon_Result>("BD_InQRCode1TuChon", soPoParameter, maSKUParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_ChiTietKhac_Result> App_XuatHangTrang_ChiTietKhac(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_ChiTietKhac_Result>("App_XuatHangTrang_ChiTietKhac", nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_XuatHangTrang_UpdateQRCodeKhac_Result> App_XuatHangTrang_UpdateQRCodeKhac(Nullable<int> nguoiDung, string ghiChu, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatHangTrang_UpdateQRCodeKhac_Result>("App_XuatHangTrang_UpdateQRCodeKhac", nguoiDungParameter, ghiChuParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<BD_LichSuQuetSanXuat_Result> BD_LichSuQuetSanXuat(string soEPI, string maSKU, string maCongDoan)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_LichSuQuetSanXuat_Result>("BD_LichSuQuetSanXuat", soEPIParameter, maSKUParameter, maCongDoanParameter);
        }
    
        public virtual ObjectResult<app_TruLenConDanhSach_Result> app_TruLenConDanhSach(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_TruLenConDanhSach_Result>("app_TruLenConDanhSach", nguoiDungParameter);
        }
    
        public virtual ObjectResult<App_TruLenContQRCode_Result> App_TruLenContQRCode(Nullable<int> nguoiDung, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_TruLenContQRCode_Result>("App_TruLenContQRCode", nguoiDungParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<App_XuatThanhPhamKhac_Result> App_XuatThanhPhamKhac(Nullable<int> nguoiDung)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_XuatThanhPhamKhac_Result>("App_XuatThanhPhamKhac", nguoiDungParameter);
        }
    
        public virtual ObjectResult<app_XuatThanhPhamKhac_UpdateQRCode_Result> app_XuatThanhPhamKhac_UpdateQRCode(Nullable<int> nguoiDung, string ghiChu, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_XuatThanhPhamKhac_UpdateQRCode_Result>("app_XuatThanhPhamKhac_UpdateQRCode", nguoiDungParameter, ghiChuParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoTongTon_Result> BD_BaoCaoTongTon(string maSP, string maSKU)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoTongTon_Result>("BD_BaoCaoTongTon", maSPParameter, maSKUParameter);
        }
    
        public virtual ObjectResult<app_QuetThongTinQR1_Result> app_QuetThongTinQR1(string qRCode, string loai)
        {
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_QuetThongTinQR1_Result>("app_QuetThongTinQR1", qRCodeParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> bd_InQRCode1SoOF(Nullable<long> iDPoChiTiet, Nullable<int> soLuongPO, Nullable<int> soCanIn)
        {
            var iDPoChiTietParameter = iDPoChiTiet.HasValue ?
                new ObjectParameter("IDPoChiTiet", iDPoChiTiet) :
                new ObjectParameter("IDPoChiTiet", typeof(long));
    
            var soLuongPOParameter = soLuongPO.HasValue ?
                new ObjectParameter("SoLuongPO", soLuongPO) :
                new ObjectParameter("SoLuongPO", typeof(int));
    
            var soCanInParameter = soCanIn.HasValue ?
                new ObjectParameter("SoCanIn", soCanIn) :
                new ObjectParameter("SoCanIn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("bd_InQRCode1SoOF", iDPoChiTietParameter, soLuongPOParameter, soCanInParameter);
        }
    
        public virtual ObjectResult<app_SanXuat_UpdateQrCodeNhanh_Result> app_SanXuat_UpdateQrCodeNhanh(Nullable<int> nguoiDung, string maCongDoan, Nullable<int> stt, Nullable<int> idLenhRaiHang, Nullable<int> numOf, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            var sttParameter = stt.HasValue ?
                new ObjectParameter("Stt", stt) :
                new ObjectParameter("Stt", typeof(int));
    
            var idLenhRaiHangParameter = idLenhRaiHang.HasValue ?
                new ObjectParameter("IdLenhRaiHang", idLenhRaiHang) :
                new ObjectParameter("IdLenhRaiHang", typeof(int));
    
            var numOfParameter = numOf.HasValue ?
                new ObjectParameter("NumOf", numOf) :
                new ObjectParameter("NumOf", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_SanXuat_UpdateQrCodeNhanh_Result>("app_SanXuat_UpdateQrCodeNhanh", nguoiDungParameter, maCongDoanParameter, sttParameter, idLenhRaiHangParameter, numOfParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<BD_LichSuXuatHangTrang_Result> BD_LichSuXuatHangTrang(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maKe, string soEPI, string maSKU, string maSP)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_LichSuXuatHangTrang_Result>("BD_LichSuXuatHangTrang", tuNgayParameter, denNgayParameter, maKeParameter, soEPIParameter, maSKUParameter, maSPParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoChiTietHangThanhPhamTrongKho_Result> BD_BaoCaoChiTietHangThanhPhamTrongKho(string maSKU, string maKe, string maSP, string soEPI)
        {
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoChiTietHangThanhPhamTrongKho_Result>("BD_BaoCaoChiTietHangThanhPhamTrongKho", maSKUParameter, maKeParameter, maSPParameter, soEPIParameter);
        }
    
        public virtual ObjectResult<BD_BaoCaoNhapHangTrangChiTiet_Result> BD_BaoCaoNhapHangTrangChiTiet(string maSP, string maSKU, string maKe)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_BaoCaoNhapHangTrangChiTiet_Result>("BD_BaoCaoNhapHangTrangChiTiet", maSPParameter, maSKUParameter, maKeParameter);
        }
    
        public virtual ObjectResult<App_SanXuat_UpdateQrCodeBackup_Result> App_SanXuat_UpdateQrCodeBackup(Nullable<int> nguoiDung, string maCongDoan, Nullable<int> stt, Nullable<int> idLenhRaiHang, Nullable<int> numOf, string qRCode)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("NguoiDung", nguoiDung) :
                new ObjectParameter("NguoiDung", typeof(int));
    
            var maCongDoanParameter = maCongDoan != null ?
                new ObjectParameter("MaCongDoan", maCongDoan) :
                new ObjectParameter("MaCongDoan", typeof(string));
    
            var sttParameter = stt.HasValue ?
                new ObjectParameter("Stt", stt) :
                new ObjectParameter("Stt", typeof(int));
    
            var idLenhRaiHangParameter = idLenhRaiHang.HasValue ?
                new ObjectParameter("IdLenhRaiHang", idLenhRaiHang) :
                new ObjectParameter("IdLenhRaiHang", typeof(int));
    
            var numOfParameter = numOf.HasValue ?
                new ObjectParameter("NumOf", numOf) :
                new ObjectParameter("NumOf", typeof(int));
    
            var qRCodeParameter = qRCode != null ?
                new ObjectParameter("QRCode", qRCode) :
                new ObjectParameter("QRCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_SanXuat_UpdateQrCodeBackup_Result>("App_SanXuat_UpdateQrCodeBackup", nguoiDungParameter, maCongDoanParameter, sttParameter, idLenhRaiHangParameter, numOfParameter, qRCodeParameter);
        }
    
        public virtual ObjectResult<app_ChuyenCont_Result> app_ChuyenCont(string qRCode1, string qRCode2, Nullable<long> iDLenhSX1, Nullable<long> iDLenhSX2, Nullable<int> soOF1, Nullable<int> soOF2, Nullable<int> nguoiChuyen)
        {
            var qRCode1Parameter = qRCode1 != null ?
                new ObjectParameter("QRCode1", qRCode1) :
                new ObjectParameter("QRCode1", typeof(string));
    
            var qRCode2Parameter = qRCode2 != null ?
                new ObjectParameter("QRCode2", qRCode2) :
                new ObjectParameter("QRCode2", typeof(string));
    
            var iDLenhSX1Parameter = iDLenhSX1.HasValue ?
                new ObjectParameter("IDLenhSX1", iDLenhSX1) :
                new ObjectParameter("IDLenhSX1", typeof(long));
    
            var iDLenhSX2Parameter = iDLenhSX2.HasValue ?
                new ObjectParameter("IDLenhSX2", iDLenhSX2) :
                new ObjectParameter("IDLenhSX2", typeof(long));
    
            var soOF1Parameter = soOF1.HasValue ?
                new ObjectParameter("SoOF1", soOF1) :
                new ObjectParameter("SoOF1", typeof(int));
    
            var soOF2Parameter = soOF2.HasValue ?
                new ObjectParameter("SoOF2", soOF2) :
                new ObjectParameter("SoOF2", typeof(int));
    
            var nguoiChuyenParameter = nguoiChuyen.HasValue ?
                new ObjectParameter("NguoiChuyen", nguoiChuyen) :
                new ObjectParameter("NguoiChuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_ChuyenCont_Result>("app_ChuyenCont", qRCode1Parameter, qRCode2Parameter, iDLenhSX1Parameter, iDLenhSX2Parameter, soOF1Parameter, soOF2Parameter, nguoiChuyenParameter);
        }
    
        public virtual ObjectResult<app_DanhSachChuyenCont_Result> app_DanhSachChuyenCont()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_DanhSachChuyenCont_Result>("app_DanhSachChuyenCont");
        }
    
        public virtual ObjectResult<BD_ChuyenKeThanhPham_Result> BD_ChuyenKeThanhPham(string maKe, string maChiTietSP)
        {
            var maKeParameter = maKe != null ?
                new ObjectParameter("MaKe", maKe) :
                new ObjectParameter("MaKe", typeof(string));
    
            var maChiTietSPParameter = maChiTietSP != null ?
                new ObjectParameter("MaChiTietSP", maChiTietSP) :
                new ObjectParameter("MaChiTietSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BD_ChuyenKeThanhPham_Result>("BD_ChuyenKeThanhPham", maKeParameter, maChiTietSPParameter);
        }
    
        public virtual ObjectResult<Proc_XemTienDoSanXuat_Result> Proc_XemTienDoSanXuat(string soEPI, string maSKU)
        {
            var soEPIParameter = soEPI != null ?
                new ObjectParameter("SoEPI", soEPI) :
                new ObjectParameter("SoEPI", typeof(string));
    
            var maSKUParameter = maSKU != null ?
                new ObjectParameter("MaSKU", maSKU) :
                new ObjectParameter("MaSKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_XemTienDoSanXuat_Result>("Proc_XemTienDoSanXuat", soEPIParameter, maSKUParameter);
        }
    }
}
